MvcSeguridadCubosJPL/Models/CompraCubo.cs
namespace MvcSeguridadCubosJPL.Models
{
    public class CompraCubo
    {
        public int IdPedido { get; set; }
        public int IdCubo { get; set; }
        public int IdUsuario { get; set; }
        public DateTime FechaPedido { get; set; }
    }
}

MvcSeguridadCubosJPL/Models/Cubo.cs
namespace MvcSeguridadCubosJPL.Models
{
    public class Cubo
    {
        public int IdCubo { get; set; }
        public string Nombre { get; set; }
        public string Marca { get; set; }
        public string Imagen { get; set; }
        public int Precio { get; set; }
    }
}

MvcSeguridadCubosJPL/Models/ErrorViewModel.cs
namespace MvcSeguridadCubosJPL.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

MvcSeguridadCubosJPL/Models/LoginModel.cs
namespace MvcSeguridadCubosJPL.Models
{
    public class LoginModel
    {
        public string Email { get; set; }
        public string Password { get; set; }
    }
}

MvcSeguridadCubosJPL/Models/Usuario.cs
namespace MvcSeguridadCubosJPL.Models
{
    public class Usuario
    {
       
        public int IdUsuario { get; set; }
        public string Nombre { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public string Imagen { get; set; }
    }
}

MvcSeguridadCubosJPL/Controllers/CubosController.cs
using Microsoft.AspNetCore.Mvc;
using MvcSeguridadCubosJPL.Filters;
using MvcSeguridadCubosJPL.Models;
using MvcSeguridadCubosJPL.Services;

namespace MvcSeguridadCubosJPL.Controllers
{
    public class CubosController : Controller
    {
        private ServiceApiCubos service;

        public CubosController(ServiceApiCubos service)
        {
            this.service = service;
        }

        //METODO PARA SACAR TODOS LOS CUBOS
        public async Task<IActionResult> Index()
        {
            
                List<Cubo> cubos =
                    await this.service.GetCubosAsync();
                return View(cubos);
            

        }
        public async Task<IActionResult> FindCuboAsync()
        {
            return View();
        }
        [HttpPost]
        //METODO PARA BUSCAR CUBO POR MARCA
        public async  Task<ActionResult<List<Cubo>>> FindCuboAsync(string marca)
        {
            List<Cubo> cubos = await this.service.FindCuboAsync(marca);
            return View(cubos);
        }

        [AuthorizeUsuarios]
        public async Task<IActionResult> Perfil()
        {
            string token =
                HttpContext.Session.GetString("TOKEN");
            Usuario user = await
                this.service.GetPerfilUsuarioAsync(token);
            return View(user);
        }

        public async Task<IActionResult> CreateCubo()
        {
            return View();
        }


        [HttpPost]
        public async Task<IActionResult> CreateCubo(Cubo cubo)
        {
            await this.service.InsertCuboAsync(cubo.IdCubo, cubo.Nombre,
                cubo.Marca, cubo.Imagen, cubo.Precio);
            return RedirectToAction("Index", "Cubos");
        }
    }
}

MvcSeguridadCubosJPL/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using MvcSeguridadCubosJPL.Models;
using System.Diagnostics;

namespace MvcSeguridadCubosJPL.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

MvcSeguridadCubosJPL/Controllers/ManagedController.cs
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Mvc;
using MvcSeguridadCubosJPL.Models;
using MvcSeguridadCubosJPL.Services;
using System.Security.Claims;

namespace MvcSeguridadCubosJPL.Controllers
{
    public class ManagedController : Controller
    {
        private ServiceApiCubos service;

        public ManagedController(ServiceApiCubos service)
        {
            this.service = service;
        }

        public IActionResult Login()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Login
     (string email, string password)
        {
            string token =
                await this.service.GetTokenAsync(email, password);
            if (token == null)
            {
                ViewData["MENSAJE"] = "Email/Password incorrectos";
                return View();
            }
            else
            {
                ViewData["MENSAJE"] = "Bienvenid@ a mi App!!!";
                HttpContext.Session.SetString("TOKEN", token);
                ClaimsIdentity identity =
                    new ClaimsIdentity
                    (CookieAuthenticationDefaults.AuthenticationScheme,
                    ClaimTypes.Name, ClaimTypes.Role);
                identity.AddClaim(new Claim(ClaimTypes.Name, email));
                identity.AddClaim(new Claim(ClaimTypes.NameIdentifier, password));
                ClaimsPrincipal userPrincipal = new ClaimsPrincipal(identity);
                await HttpContext.SignInAsync
                    (CookieAuthenticationDefaults.AuthenticationScheme
                    , userPrincipal, new AuthenticationProperties
                    {
                        ExpiresUtc = DateTime.UtcNow.AddMinutes(30)
                    });
                return RedirectToAction("Index", "Cubos");
            }
        }

        public async Task<IActionResult> Logout()
        {
            await HttpContext.SignOutAsync
                (CookieAuthenticationDefaults.AuthenticationScheme);
            HttpContext.Session.Remove("TOKEN");
            return RedirectToAction("Index", "Home");
        }

        public async Task<IActionResult> Register()
        {
            return View();
        }


        [HttpPost]
        public async Task<IActionResult> Register(Usuario user)
        {
            await this.service.InsertUsuarioAsync(user.IdUsuario, user.Nombre,
                user.Email, user.Password, user.Imagen);
            return RedirectToAction("Index", "Cubos");
        }

    }
}

MvcSeguridadCubosJPL/Views/Cubos/CreateCubo.cshtml
@model MvcSeguridadCubosJPL.Models.Cubo

@{
    ViewData["Title"] = "CreateCubo";
}

<h1>CreateCubo</h1>

<h4>Cubo</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="CreateCubo">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="IdCubo" class="control-label"></label>
                <input asp-for="IdCubo" class="form-control" />
                <span asp-validation-for="IdCubo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Nombre" class="control-label"></label>
                <input asp-for="Nombre" class="form-control" />
                <span asp-validation-for="Nombre" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Marca" class="control-label"></label>
                <input asp-for="Marca" class="form-control" />
                <span asp-validation-for="Marca" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Imagen" class="control-label"></label>
                <input asp-for="Imagen" class="form-control" />
                <span asp-validation-for="Imagen" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Precio" class="control-label"></label>
                <input asp-for="Precio" class="form-control" />
                <span asp-validation-for="Precio" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MvcSeguridadCubosJPL/Views/Cubos/FindCubo.cshtml
@model IEnumerable<MvcSeguridadCubosJPL.Models.Cubo>

@{
    ViewData["Title"] = "FindCubo";
}

<h1>Buscar cubo por marca</h1>

<form method="post">
    <label>Marca:</label>
    <input type="text" name="marca" class="form-control" />
    <button class="btn btn-info">Buscar</button>
</form>
@if(Model != null){

    <table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.IdCubo)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Nombre)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Marca)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Imagen)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Precio)
            </th>
            
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.IdCubo)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Nombre)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Marca)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Imagen)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Precio)
            </td>
           
        </tr>
}
    </tbody>
</table>

}

MvcSeguridadCubosJPL/Views/Cubos/Index.cshtml
@model IEnumerable<MvcSeguridadCubosJPL.Models.Cubo>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.IdCubo)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Nombre)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Marca)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Imagen)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Precio)
            </th>
            <th>Comprar</th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.IdCubo)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Nombre)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Marca)
            </td>
            <td>
               <img src=" @Html.DisplayFor(modelItem => item.Imagen)">
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Precio)
            </td>
            <td>
                <button class="btn btn-dark">comprar</button>
            </td>
        </tr>
}
    </tbody>
</table>

MvcSeguridadCubosJPL/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

MvcSeguridadCubosJPL/Views/Managed/Login.cshtml
<h1>LOGIN</h1>

<form method="post">
    <label>EMAIL:</label>
    <input type="text" placeholder="email" name="email"/>
    <label>PASSWORD:</label>
    <input type="text" placeholder="password" name="password"/>
    <button class="btn btn-info">LOG IN</button>
</form>

<h3>@ViewData["MENSAJE"]</h3>

MvcSeguridadCubosJPL/Views/Managed/Register.cshtml
@model MvcSeguridadCubosJPL.Models.Usuario

@{
    ViewData["Title"] = "Register";
}

<h1>Register</h1>

<h4>Usuario</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Register">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="IdUsuario" class="control-label"></label>
                <input asp-for="IdUsuario" class="form-control" />
                <span asp-validation-for="IdUsuario" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Nombre" class="control-label"></label>
                <input asp-for="Nombre" class="form-control" />
                <span asp-validation-for="Nombre" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Password" class="control-label"></label>
                <input asp-for="Password" class="form-control" />
                <span asp-validation-for="Password" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Imagen" class="control-label"></label>
                <input asp-for="Imagen" class="form-control" />
                <span asp-validation-for="Imagen" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MvcSeguridadCubosJPL/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MvcSeguridadCubosJPL</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MvcSeguridadCubosJPL.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MvcSeguridadCubosJPL</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Cubos" asp-action="Index">Cubos</a>
                        </li>
                         <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Cubos" asp-action="CreateCubo">Crear Cubos</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Managed" asp-action="Register">Crear nuevo usuario</a>
                        </li>
                       <partial name="_MenuUsuario" />
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - MvcSeguridadCubosJPL - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

MvcSeguridadCubosJPL/Views/Shared/_MenuUsuario.cshtml
@if (Context.User.Identity.IsAuthenticated){
    <li class="nav-item">
        <a class="nav-link text-danger"
       asp-controller="Cubos"
       asp-action="Index">
            Cubos
        </a>
    </li>
    <li class="nav-item">
        <a class="nav-link text-danger"
       asp-controller="Cubos"
       asp-action="Perfil">
            Mi Perfil
        </a>
    </li>
     <li class="nav-item">
        <a class="nav-link text-danger"
       asp-controller="Cubos"
       asp-action="FindCubo">
            Buscar cubo
        </a>
    </li>

    <li class="nav-item">
        <a class="nav-link text-dark"
       asp-controller="Managed"
       asp-action="Logout">
            Log Out
            <span style="color:blue">@Context.User.Identity.Name</span>
        </a>
    </li>
}else{
    <li class="nav-item">
        <a class="nav-link text-danger"
            asp-controller="Managed"
            asp-action="Login">
            Log In
        </a>
    </li>
}